export default {
  url: 'https://gitlab.com/api/v4/projects/70348379/repository/files/',
  languages: ['en', 'fr', 'es', 'pt'], //, 'de', 'br', 'eo', 'ro', 'zh', 'ar', 'el', 'ko', 'ru', 'fi', 'vi'
  books: [
    { "id": "gn", "pt": "Gênesis", "en": "Genesis", "fr": "Genèse", "es": "Génesis" },
    { "id": "ex", "pt": "Êxodo", "en": "Exodus", "fr": "Exode", "es": "Éxodo" },
    { "id": "lv", "pt": "Levítico", "en": "Leviticus", "fr": " Lévitique", "es": "Levítico" },
    { "id": "nm", "pt": "Números", "en": "Numbers", "fr": " Nombres", "es": "Números" },
    { "id": "dt", "pt": "Deuteronômio", "en": "Deuteronomy", "fr": " Deutéronome", "es": "Deuteronomio" },
    { "id": "js", "pt": "Josué", "en": "Joshua", "fr": "  Josué", "es": "Josué" },
    { "id": "jud", "pt": "Juízes", "en": "Judges", "fr": "  Juges", "es": "Jueces" },
    { "id": "rt", "pt": "Rute", "en": "Ruth", "fr": " Ruth", "es": "Rut" },
    { "id": "1sm", "pt": "1 Samuel", "en": "1 Samuel", "fr": "1 Samuel", "es": "1 Samuel" },
    { "id": "2sm", "pt": "2 Samuel", "en": "2 Samuel", "fr": "2 Samuel", "es": "2 Samuel" },
    { "id": "1kgs", "pt": "1 Reis", "en": "1 Kings", "fr": "1 Rois", "es": "1 Reyes" },
    { "id": "2kgs", "pt": "2 Reis", "en": "3 Kings", "fr": "2 Rois", "es": "2 Reyes" },
    { "id": "1ch", "pt": "1 Crônicas", "en": "1 Chronicles", "fr": "1 Chroniques", "es": "1 Crónicas" },
    { "id": "2ch", "pt": "2 Crônicas", "en": "2 Chronicles", "fr": "2 Chroniques", "es": "2 Crónicas" },
    { "id": "ez", "pt": "Esdras", "en": "Ezra", "fr": "Esdras", "es": "Esdras" },
    { "id": "ne", "pt": "Neemias", "en": "Nehemiah", "fr": "Néhémie", "es": "Nehemías" },
    { "id": "et", "pt": "Ester", "en": "Esther", "fr": " Esther", "es": "Ester" },
    { "id": "job", "pt": "Jó", "en": "Job", "fr": " Job", "es": "Job" },
    { "id": "ps", "pt": "Salmos", "en": "Psalm", "fr": " Psaume", "es": "Salmos" },
    { "id": "prv", "pt": "Provérbios", "en": "Proverbs", "fr": "Proverbes", "es": "Proverbios" },
    { "id": "ec", "pt": "Eclesiastes", "en": "Ecclesiastes", "fr": "Ecclésiaste", "es": "Eclesiastés" },
    { "id": "so", "pt": "Cânticos", "en": "Songs of Solomon", "fr": "Cantique des Cantiqu", "es": "Cantar de los Cantares" },
    { "id": "is", "pt": "Isaías", "en": "Isaiah", "fr": "Ésaïe", "es": "Isaías" },
    { "id": "jr", "pt": "Jeremias", "en": "Jeremiah", "fr": "Jérémie", "es": "Jeremías" },
    { "id": "lm", "pt": "Lamentações de Jeremias", "en": "Lamentations", "fr": " Lamentations", "es": "Lamentaciones" },
    { "id": "ez", "pt": "Ezequiel", "en": "Ezekiel", "fr": "Ézéchiel", "es": "Ezequiel" },
    { "id": "dn", "pt": "Daniel", "en": "Daniel", "fr": "Daniel", "es": "Daniel" },
    { "id": "ho", "pt": "Oséias", "en": "Hosea", "fr": "Osée", "es": "Oseas" },
    { "id": "jl", "pt": "Joel", "en": "Joel", "fr": "Joël", "es": "Joel" },
    { "id": "am", "pt": "Amós", "en": "Amos", "fr": "Amos", "es": "Amós" },
    { "id": "ob", "pt": "Obadias", "en": "Obadiah", "fr": "Abdias", "es": "Abdías" },
    { "id": "jn", "pt": "Jonas", "en": "Jonah", "fr": "Jonas", "es": "Jonás" },
    { "id": "mi", "pt": "Miquéias", "en": "Micah", "fr": "Michée", "es": "Miqueas" },
    { "id": "na", "pt": "Naum", "en": "Nahum", "fr": "Nahum", "es": "Nahún" },
    { "id": "hk", "pt": "Habacuque", "en": "Habakkuk", "fr": "Habacuc", "es": "Habacuc" },
    { "id": "zp", "pt": "Sofonias", "en": "Zephaniah", "fr": "Sophonie", "es": "Sofonías" },
    { "id": "hg", "pt": "Ageu", "en": "Haggai", "fr": "Aggée", "es": "Ageo" },
    { "id": "zc", "pt": "Zacarias", "en": "Zechariah", "fr": "Zacharie", "es": "Zacarías" },
    { "id": "ml", "pt": "Malaquias", "en": "Malachi", "fr": "Malachie", "es": "Malaquías" },
    { "id": "mt", "pt": "Mateus", "en": "Matthew", "fr": "Matthieu", "es": "Mateo" },
    { "id": "mk", "pt": "Marcos", "en": "Mark", "fr": "Marc", "es": "Marcos" },
    { "id": "lk", "pt": "Lucas", "en": "Luke", "fr": "Luc", "es": "Lucas" },
    { "id": "jo", "pt": "João", "en": "John", "fr": "Jean", "es": "Juan" },
    { "id": "act", "pt": "Atos", "en": "Acts", "fr": "Actes", "es": "Hechos de los Apóstoles" },
    { "id": "rm", "pt": "Romanos", "en": "Romans", "fr": "Romains", "es": "Romanos" },
    { "id": "1co", "pt": "1 Coríntios", "en": "1 Corinthians", "fr": "1 Corinthiens", "es": "1 Corintios" },
    { "id": "2co", "pt": "2 Coríntios", "en": "2 Corinthians", "fr": "2 Corinthiens", "es": "2 Corintios" },
    { "id": "gl", "pt": "Gálatas", "en": "Galatians", "fr": "Galates", "es": "Gálatas" },
    { "id": "eph", "pt": "Efésios", "en": "Ephesians", "fr": "Éphésiens", "es": "Efesios" },
    { "id": "ph", "pt": "Filipenses", "en": "Philippians", "fr": "Philippiens", "es": "Filipenses" },
    { "id": "cl", "pt": "Colossenses", "en": "Colossians", "fr": "Colossiens", "es": "Colosenses" },
    { "id": "1ts", "pt": "1 Tessalonicenses", "en": "1 Thessalonians", "fr": "1 Thessaloniciens", "es": "" },
    { "id": "2ts", "pt": "2 Tessalonicenses", "en": "2 Thessalonians", "fr": "2 Thessaloniciens", "es": "" },
    { "id": "1tm", "pt": "1 Timóteo", "en": "1 Timothy", "fr": "1 Timothée", "es": "1 Tesalonicenses" },
    { "id": "2tm", "pt": "2 Timóteo", "en": "2 Timothy", "fr": "2 Timothée", "es": "2 Tesalonicenses" },
    { "id": "tt", "pt": "Tito", "en": "Titus", "fr": "Tite", "es": "Tito" },
    { "id": "phm", "pt": "Filemom", "en": "Philemon", "fr": "Philémon", "es": "Filemón" },
    { "id": "hb", "pt": "Hebreus", "en": "Hebrews", "fr": "Hébreux", "es": "Hebreos" },
    { "id": "jm", "pt": "Tiago", "en": "James", "fr": "Jacques", "es": "Santiago" },
    { "id": "1pe", "pt": "1 Pedro", "en": "1 Peter", "fr": "1 Pierre", "es": "1 Pedro" },
    { "id": "2pe", "pt": "2 Pedro", "en": "2 Peter", "fr": "2 Pierre", "es": "2 Pedro" },
    { "id": "1jo", "pt": "1 João", "en": "1 John", "fr": "1 Jean", "es": "1 Juan" },
    { "id": "2jo", "pt": "2 João", "en": "2 John", "fr": "2 Jean", "es": "2 Juan" },
    { "id": "3jo", "pt": "3 João", "en": "3 John", "fr": "3 Jean", "es": "3 Juan" },
    { "id": "jd", "pt": "Judas", "en": "Jude", "fr": "Jude", "es": "Judas" },
    { "id": "re", "pt": "Apocalipse", "en": "Revelation", "fr": "Apocalypse", "es": "Apocalipsis" }
  ]
}
